# Generated by Django 3.0.6 on 2020-07-07 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_rule', models.CharField(choices=[('PREV_30_DAYS', 'PREV 30 DAYS'), ('PREV_MONTH', 'PREV MONTH'), ('PREV_2_MONTHS', 'PREV 2 MONTHS'), ('PREV_3_MONTHS', 'PREV 3 MONTHS'), ('PREV_6_MONTHS', 'PREV 6 MONTHS'), ('PREV_12_MONTHS', 'PREV 12 MONTHS'), ('PREV_QUARTER', 'PREV QUARTER'), ('PREV_HALF', 'PREV HALF'), ('PREV_YEAR', 'PREV YEAR'), ('ALWAYS', 'ALWAYS')], max_length=20, verbose_name='Discount period basis')),
                ('smooth_cumulative', models.BooleanField(default=True, verbose_name='Smooth cumulative discount')),
                ('smooth_per_order', models.BooleanField(default=True, verbose_name='Smooth per-order discount')),
            ],
            options={
                'verbose_name': 'Discount policy',
                'verbose_name_plural': 'Discount policies',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Group title')),
                ('handle', models.SlugField(help_text='case insensitive', max_length=32, unique=True, verbose_name='Handle')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.AddField(
            model_name='currency',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Currency is disabled for being used', verbose_name='Disabled'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Currency name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=10, verbose_name='Currency symbol'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol_before',
            field=models.BooleanField(default=False, verbose_name='Currency symbol before value'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', related_query_name='product', to='store.Unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('Item', 'Item'), ('Weight', 'Weight'), ('Length', 'Length'), ('Volume', 'Volume'), ('Voltage', 'Voltage'), ('Power', 'Power')], max_length=20, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='PerOrderStepping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.BigIntegerField(verbose_name='Order summ')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount value')),
                ('discount_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.DiscountPolicy', verbose_name='Discount policy')),
            ],
            options={
                'verbose_name': 'Order summ step',
                'verbose_name_plural': 'Order summ steps',
            },
        ),
        migrations.CreateModel(
            name='DiscountPolicyStepping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.BigIntegerField(verbose_name='Cumulative orders summ')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount value')),
                ('discount_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.DiscountPolicy', verbose_name='Discount policy')),
            ],
            options={
                'verbose_name': 'Cumulative orders summ step',
                'verbose_name_plural': 'Cumulative orders summ steps',
            },
        ),
        migrations.AddField(
            model_name='discountpolicy',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.Group', verbose_name='Products group'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_updated', models.DateTimeField()),
                ('discount_valid_till', models.DateTimeField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Currency')),
                ('discount_policy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.DiscountPolicy')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.PriceType')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('user.user',),
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=2, verbose_name='Country ISO Alpha-2 code')),
                ('name', models.CharField(max_length=200, verbose_name='Country name')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], help_text='Only hardcoded languages available', max_length=2, verbose_name='Langiage')),
                ('post_code_rule', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], help_text='Post index verification regular expression', max_length=100, verbose_name='Langiage')),
                ('disabled', models.BooleanField(help_text='Country is disabled for being used', verbose_name='Disabled')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Country',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='store.Group', verbose_name='Group'),
            preserve_default=False,
        ),
    ]
