# Generated by Django 3.0.6 on 2020-10-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountpolicy',
            name='smooth_cumulative',
            field=models.BooleanField(default=True, help_text='', verbose_name='Smooth cumulative discount'),
        ),
    ]
