# Generated by Django 3.0.6 on 2020-07-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200707_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField(default=None)),
                ('end_at', models.DateField(default=None)),
            ],
            options={
                'verbose_name': 'Promo Action',
                'verbose_name_plural': 'Promo Actions',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.Currency'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='discount_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.DiscountPolicy'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='discount_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='discount_valid_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.PriceType'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=10, verbose_name='Post code')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('door_code', models.CharField(max_length=200, verbose_name='Door code')),
                ('comment', models.CharField(max_length=1000, verbose_name='Address comment')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=11, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitude')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Country', verbose_name='Country')),
            ],
        ),
    ]
