# Generated by Django 3.0.6 on 2020-10-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201011_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='test',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_type',
            field=models.IntegerField(choices=[(1, 'Integer value'), (2, 'Float value'), (3, 'Fixed decimal value, 1 digit after comma'), (4, 'Fixed decimal value, 2 digits after comma'), (5, 'Fixed decimal value, 3 digits after comma'), (6, 'Enum'), (7, 'String value'), (8, 'Set')], default=7),
        ),
    ]
