# Generated by Django 3.0.6 on 2020-07-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200707_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='discount_updated',
        ),
        migrations.AlterField(
            model_name='customer',
            name='discount_valid_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
