# Generated by Django 3.0.6 on 2020-07-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200707_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='handle',
            field=models.CharField(max_length=2, unique=True, verbose_name='Country ISO Alpha-2 code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], help_text='Only hardcoded languages available', max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='country',
            name='post_code_rule',
            field=models.CharField(max_length=100),
        ),
    ]
