# Generated by Django 3.0.6 on 2020-07-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200707_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.Currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='country',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Country is disabled for being used', verbose_name='Disabled'),
        ),
        migrations.AlterField(
            model_name='country',
            name='language',
            field=models.CharField(blank=True, choices=[('ru', 'Русский'), ('en', 'English')], help_text='Only hardcoded languages available', max_length=2, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='country',
            name='post_code_rule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
