# Generated by Django 3.0.6 on 2020-07-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200707_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='door_code',
        ),
        migrations.AddField(
            model_name='address',
            name='address1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Street, Home'),
        ),
        migrations.AddField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Office/Apartment/Room'),
        ),
        migrations.AddField(
            model_name='address',
            name='doorphone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Doorphone'),
        ),
    ]
